name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'
      - name: Build & run unit tests (arm64)
        run: |
          set -euo pipefail
          xcodebuild \
            -project weaver.xcodeproj \
            -scheme weaver \
            -destination 'platform=macOS,arch=arm64' \
            -sdk macosx \
            -destination-timeout 10 \
            CODE_SIGNING_ALLOWED=NO \
            -skipPackagePluginValidation -skipMacroValidation \
            -only-testing:weaverTests \
            test | tee test.log | cat

