name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Build and Test
        run: |
          set -euo pipefail
          xcodebuild -project weaver.xcodeproj -scheme weaver -destination 'platform=macOS' -skipPackagePluginValidation -skipMacroValidation build | tee build.log | cat
          xcodebuild -project weaver.xcodeproj -scheme weaver -destination 'platform=macOS' -skipPackagePluginValidation -skipMacroValidation test | tee test.log | cat

