name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'
      - name: Build and Test
        run: |
          set -euo pipefail
          xcodebuild -project weaver.xcodeproj -scheme weaver -destination 'platform=macOS' -skipPackagePluginValidation -skipMacroValidation build | tee build.log | cat
          xcodebuild -project weaver.xcodeproj -scheme weaver -destination 'platform=macOS' -skipPackagePluginValidation -skipMacroValidation test | tee test.log | cat

