name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'
      - name: Build (Release)
        run: |
          set -euo pipefail
          xcodebuild -project weaver.xcodeproj -scheme weaver -configuration Release -destination 'platform=macOS' \
            CODE_SIGNING_ALLOWED=NO -archivePath build/weaver.xcarchive archive | tee build.log | cat
          mkdir -p artifacts
          ditto -c -k --keepParent build/weaver.xcarchive/Products/Applications/weaver.app artifacts/weaver.zip || true
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/weaver.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

